# Generated by Django 4.1.3 on 2024-12-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individuals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=200)),
                ('assistance_type', models.CharField(max_length=200)),
                ('geolocation', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField()),
                ('extended_assistance', models.BooleanField(default=False)),
                ('observation', models.TextField(blank=True, null=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='individuals.individual')),
            ],
        ),
    ]
