# Generated by Django 4.1.3 on 2025-01-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='assistance_type',
            field=models.CharField(max_length=200, verbose_name='assistance type'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='author',
            field=models.CharField(max_length=200, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date and time'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='details',
            field=models.TextField(verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='extended_assistance',
            field=models.BooleanField(default=False, verbose_name='follow-up status'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='geolocation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='geolocation'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='observation'),
        ),
    ]
