# Generated by Django 4.1.3 on 2025-01-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistances', '0002_alter_assistance_assistance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='assistance_type',
            field=models.CharField(max_length=100, verbose_name='assistance type'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='author',
            field=models.CharField(max_length=100, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='details',
            field=models.TextField(blank=True, default='-', verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='extended_assistance',
            field=models.BooleanField(default=False, verbose_name='follow-up needed'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='geolocation',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='geolocation'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='observation',
            field=models.TextField(blank=True, default='-', verbose_name='observation'),
        ),
    ]
