# Generated by Django 4.1.3 on 2025-01-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistances', '0003_alter_assistance_assistance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='geolocation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='geolocation'),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='observation'),
        ),
    ]
