# Generated by Django 4.1.3 on 2024-12-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('reference_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.TextField()),
                ('is_fixed_or_transitory_place', models.BooleanField(default=False)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('life_center', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
