# Generated by Django 4.1.3 on 2025-01-03 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='last_name',
        ),
        migrations.AddField(
            model_name='individual',
            name='name',
            field=models.CharField(blank='True', max_length=100, null='True', verbose_name='name'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='individual',
            name='surname',
            field=models.CharField(blank='True', max_length=100, null='True', verbose_name='surname'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='individual',
            name='birth_date',
            field=models.DateField(verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='contact info'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='dni',
            field=models.CharField(blank=True, max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='DNI must be an 8-digit number', regex='^\\d{8}$')], verbose_name='dni'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='is_fixed_or_transitory_place',
            field=models.BooleanField(default=False, verbose_name='location status'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='life_center',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='life center'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='location',
            field=models.TextField(verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='reference_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='reference phone'),
        ),
    ]
