# Generated by Django 4.1.3 on 2025-01-03 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0002_remove_individual_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='birth_date',
            field=models.DateField(default='-', help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='contact_info',
            field=models.TextField(blank=True, default='-', verbose_name='contact info'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='dni',
            field=models.CharField(blank=True, default='-', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='DNI must be an 8-digit number', regex='^\\d{8}$')], verbose_name='dni'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='is_fixed_or_transitory_place',
            field=models.BooleanField(default=False, verbose_name='transitory location'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='life_center',
            field=models.CharField(blank=True, default='-', max_length=100, verbose_name='life center'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='location',
            field=models.TextField(default='-', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(blank=True, default='-', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='nickname',
            field=models.CharField(blank=True, default='-', max_length=100, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='phone_number',
            field=models.CharField(default='-', max_length=15, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='reference_phone_number',
            field=models.CharField(blank=True, default='-', max_length=15, verbose_name='reference phone'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='surname',
            field=models.CharField(blank=True, default='-', max_length=100, verbose_name='surname'),
        ),
    ]
