# Generated by Django 5.1.4 on 2025-01-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0004_alter_individual_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='phone'),
        ),
    ]
